[rule]
author = ["Mitch Kelsey"]
description = "Triggers when more than 1000 queries to a web server have been observed in a 5 minute window"
from = "now-6m" # this is the default value, change as needed
name = "Excessive Web Traffic"
# note = "Insert Analysis Notes Here"
risk_score = 25
severity = "low"
# tags = ["Example", "Tag"]
type = "threshold"
rule_id = "00000000-0000-0000-0000-000000000011"
query = '''
event.dataset : "zeek.http"
'''

[rule.threshold]
field = ["source.ip"]
value = 1000

[[rule.threat]] # Example Tactic, Technique, Sub-Technique
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1046"
name = "Network Service Discovery"
reference = "https://attack.mitre.org/techniques/T1046/"
# [[rule.threat.subtechnique]]
# id = "Insert Here"
# name = "Insert Here"
# reference = "Insert URL"

[[rule.threat.tactic]]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"